name: Appium Run
on:
  workflow_dispatch
  
jobs:
  build:
    environment: CI
    env:
      APP_PATH: ${{ vars.GITHUB_WORKSPACE }}/test.app
      DEVICE_NAME: iPhone 14 Pro
      PLATFORM_VERSION: 16.2
    runs-on: macos-12
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - uses: futureware-tech/simulator-action@v2
          with:
            model: $DEVICE_NAME
            os_version: $PLATFORM_VERSION
        
        - name: Download test app
          run: curl -L ${{ vars.APP_URL }} -o app.zip
    
        - name: Unzip app
          run: unzip app.zip $APP_PATH
          
        - name: Delete app
          run: rm -f app.zip
        
        - name: Install
          run: npm install
        
        - name: Test
          run: npm run test
        
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
