name: Appium Run
on:
  workflow_dispatch
  
jobs:
  build:
    environment: testing
    env:
      APP_PATH: ${{ github.workspace }}/app/test.app
      DEVICE_NAME: 'iPhone 14 Pro'
      PLATFORM_VERSION: '16.2'
    runs-on: macos-12
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup env
          run: |
            touch .env
            echo APP_PATH=$APP_PATH >> .env
            echo DEVICE_NAME=$DEVICE_NAME >> .env
            echo PLATFORM_VERSION=$PLATFORM_VERSION >> .env
        
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - name: Install Appium Server
          run: |
            npm install -g appium@next
            appium driver install xcuitest 
        
        - uses: futureware-tech/simulator-action@v2
          with:
            model: 'iPhone 14 Pro'
            os_version: '16.2'
        
        - name: Download and unzip test app
          run: |
            curl -L ${{ vars.APP_URL }} -o app.zip
            mkdir app
            unzip app.zip -d $APP_PATH
            rm -f app.zip
        
        - name: Install
          run: npm i --production
        
        - name: Run Test
          run: npm run test
