name: Appium Run
on:
  workflow_dispatch
  
jobs:
  build:
    environment: testing
    env:
      SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
      SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
      SAUCELABS_HOST: ${{ secrets.SAUCELABS_HOST }}

      APP_URL: ${{ secrets.APP_URL }}
      DEVICE_NAME: iPhone 11 Simulator
      PLATFORM_VERSION: 16.2
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup env
          run: |
            echo $DEVICE_NAME
            echo $PLATFORM_VERSION
        
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - name: Install
          run: npm i --omit=dev
        
        - name: Run Test
          run: npm run test
